base_url: http://magento-demo.lexiconn.com

implicit_timeout: 1
explicit_timeout: 10

credentials:
    default:
        login: s1iderorama@gmail.com
        psswd: codespace
    vasya:
        login: vasya@gmail.com
        psswd: superpass